### ISSUE TITLE
Perform static syntax check (lint)

### ISSUE THREAD

**Issue by agenell** [DD2480-group30/CI#7]
Add functionality to run a linter on the server code.

~~It should be runnable with a build tool such as GNU Make with a `make lint` command or equivalent.~~

There are several linters for Python such as [ruff](https://github.com/charliermarsh/ruff), [flake8](https://github.com/pycqa/flake8), etc.

**Comment by DavidCWQ** [comment]
`ruff` has been installed on the server now, we can use it for simplicity

**Comment by DavidCWQ** [comment]
Issue is resolved with the ci_build and ci_test function.
